name: deploy to lambda
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:

  deploy_zip:
    name: deploy lambda function
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.13.x]
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Build binary
        run: |
          cd example && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -a -o main main.go && zip deployment.zip main
      - name: default deploy
        uses: appleboy/lambda-action@master
        env:
          AWS_REGION: us-west-2
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_NONPROD }}
          aws_secret_access_key: ${{ secrets.AWS_ACCESS_KEY_NONPROD }}
          aws_region: us-west-2
          function_name: samplejava
          zip_file: example/deployment.zip
          memory_size: 128
          timeout: 10
          handler: foobar
          role: arn:aws:iam::989135293774:role/service-role/samplejava-role-1ilag3b3
          runtime: nodejs12.x
